const sitePreloader=document.getElementById('sitePreloader');
if(sitePreloader){
  requestAnimationFrame(()=>sitePreloader.classList.add('is-ready'));
  const dismissPreloader=()=>{
    if(sitePreloader.classList.contains('is-exiting'))return;
    sitePreloader.classList.add('is-exiting');
    document.body.classList.remove('preloader-active');
    setTimeout(()=>sitePreloader.remove(),750)
  };
  const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  setTimeout(dismissPreloader,reducedMotion?450:2550)
}

const icons={home:'<path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10v10h13V10"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>',bolt:'<path d="m13 2-9 12h8l-1 8 9-12h-8z"/>',leaf:'<path d="M20 4c-8 0-14 4-14 11 0 3 2 5 5 5 7 0 9-8 9-16Z"/><path d="M4 21c3-6 7-9 13-12"/>',message:'<path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4z"/>',gift:'<path d="M20 12v9H4v-9M2 7h20v5H2zM12 7v14"/><path d="M12 7H7.5A2.5 2.5 0 1 1 10 4.5C10 7 12 7 12 7Zm0 0h4.5A2.5 2.5 0 1 0 14 4.5C14 7 12 7 12 7Z"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 21h4"/>',chevron:'<path d="m9 18 6-6-6-6"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',plus:'<path d="M12 5v14M5 12h14"/>',play:'<path d="m8 5 11 7-11 7z"/>',video:'<rect x="3" y="5" width="14" height="14" rx="2"/><path d="m17 10 4-2v8l-4-2z"/>',send:'<path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>'};
icons.library='<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m10 9 5 3-5 3z"/>';icons.search='<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>';icons.trophy='<path d="M8 4h8v5a4 4 0 0 1-8 0z"/><path d="M8 6H4v2a4 4 0 0 0 4 4m8-6h4v2a4 4 0 0 1-4 4M12 13v4m-4 4h8m-6-4h4"/>';icons.flame='<path d="M12 22c4 0 7-3 7-7 0-3-1.5-5.5-4-8 .2 3-1 4.5-2 5-1-4-3-6-3-9-3 3-5 7-5 11 0 4.5 3 8 7 8z"/>';icons.star='<path d="m12 2 3 6 7 .9-5 4.8 1.3 6.8L12 17l-6.3 3.5L7 13.7 2 8.9 9 8z"/>';icons.medal='<circle cx="12" cy="14" r="6"/><path d="m8.5 8-3-6h5l1.5 4 1.5-4h5l-3 6m-6.5 6 2 2 4-4"/>';icons.crown='<path d="m3 7 4 4 5-7 5 7 4-4-2 11H5z"/><path d="M5 21h14"/>';icons.sun='<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>';icons.moon='<path d="M20.5 14.5A8 8 0 0 1 9.5 3.5 9 9 0 1 0 20.5 14.5Z"/>';
icons.close='<path d="m6 6 12 12M18 6 6 18"/>';icons.clock='<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>';icons.check='<path d="m5 12 4 4L19 6"/>';icons.user='<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>';icons.wallet='<path d="M4 6h15a2 2 0 0 1 2 2v11H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h13"/><path d="M16 12h5"/>';icons.activity='<path d="M3 12h4l2-6 4 12 2-6h6"/>';icons.settings='<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1A1.7 1.7 0 0 0 9 4.6 1.7 1.7 0 0 0 10 3V2.8h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1Z"/>';icons.help='<circle cx="12" cy="12" r="9"/><path d="M9.7 9a2.4 2.4 0 1 1 3.5 2.2c-.8.4-1.2.9-1.2 1.8m0 3h.01"/>';icons.shield='<path d="M12 22s8-3 8-10V5l-8-3-8 3v7c0 7 8 10 8 10Z"/>';icons.card='<rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20"/>';icons.camera='<path d="M4 8h3l2-3h6l2 3h3v11H4z"/><circle cx="12" cy="13" r="3"/>';icons.download='<path d="M12 3v12m-5-5 5 5 5-5"/><path d="M5 21h14"/>';icons.logout='<path d="M10 17l5-5-5-5m5 5H3"/><path d="M14 3h6v18h-6"/>';icons.phone='<path d="M5 3h4l2 5-3 2a15 15 0 0 0 6 6l2-3 5 2v4c0 1-1 2-2 2C10 20 4 14 3 5c0-1 1-2 2-2Z"/>';icons.document='<path d="M6 2h9l4 4v16H6z"/><path d="M14 2v5h5M9 12h7m-7 4h7"/>';
document.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[el.dataset.icon]||''}</svg>`});
const notificationToggle=document.getElementById('notificationToggle'),notificationDropdown=document.getElementById('notificationDropdown');function closeNotifications(){notificationDropdown.classList.remove('open');notificationDropdown.setAttribute('aria-hidden','true');notificationToggle.setAttribute('aria-expanded','false')}notificationToggle.addEventListener('click',event=>{event.stopPropagation();const willOpen=!notificationDropdown.classList.contains('open');notificationDropdown.classList.toggle('open',willOpen);notificationDropdown.setAttribute('aria-hidden',String(!willOpen));notificationToggle.setAttribute('aria-expanded',String(willOpen))});notificationDropdown.addEventListener('click',event=>event.stopPropagation());notificationDropdown.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',closeNotifications));document.addEventListener('click',closeNotifications);
const titles={home:'Good afternoon, Alex.',bookings:'Make time for yourself.',plans:'Built around your goals.',nutrition:'Fuel the work.',messages:'Your coach is here.',vouchers:'Give something meaningful.'};
titles.videos='Learn. Move. Progress.';
titles.rewards='Make progress rewarding.';
Object.assign(titles,{account:'Your whole app.',profilePage:'Your profile.',wallet:'Payments made simple.',membership:'Your membership.',activity:'Your progress, recorded.',workoutSummary:'Review your workout.',settings:'Make it yours.',help:'How can we help?'});
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));document.getElementById('pageTitle').textContent=titles[id]||'Holly Margot';if(id==='activity')renderAccountActivity();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));document.querySelectorAll('[data-view-link]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.viewLink)));
const modal=document.getElementById('modal'),modalTitle=document.getElementById('modalTitle'),modalText=document.getElementById('modalText');function openModal(title,text){modalTitle.textContent=title;modalText.textContent=text;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
document.querySelectorAll('[data-start]').forEach(b=>b.addEventListener('click',openWorkout));document.querySelectorAll('[data-video]').forEach(b=>b.addEventListener('click',()=>openModal(`${b.dataset.video} demo`,'Your coach’s technique video is ready. Watch the movement, then follow the cues at your own pace.')));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const toast=document.getElementById('toast');function notify(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2800)}
document.querySelector('[data-message]').addEventListener('click',()=>showView('messages'));document.getElementById('newBooking').addEventListener('click',()=>notify('Booking options are ready to choose.'));
const form=document.getElementById('messageForm');form.addEventListener('submit',e=>{e.preventDefault();const input=document.getElementById('messageInput'),value=input.value.trim();if(!value)return;const bubble=document.createElement('div');bubble.className='bubble user-bubble';bubble.innerHTML=`${value}<time>NOW</time>`;document.getElementById('chatBody').appendChild(bubble);input.value='';bubble.scrollIntoView({behavior:'smooth'});setTimeout(()=>notify('Message sent to Jordan'),250)});
document.querySelectorAll('.voucher').forEach(v=>v.addEventListener('click',()=>{document.querySelectorAll('.voucher').forEach(x=>x.classList.remove('selected'));v.classList.add('selected');document.getElementById('voucherValue').textContent=`£${v.dataset.value} gift voucher`}));document.getElementById('buyVoucher').addEventListener('click',()=>notify('Secure checkout opened for your voucher.'));

const videoModal=document.getElementById('videoModal'),youtubePlayer=document.getElementById('youtubePlayer'),videoModalTitle=document.getElementById('videoModalTitle'),youtubeLink=document.getElementById('youtubeLink');
function openVideo(id,title){videoModalTitle.textContent=title;youtubePlayer.src=`https://www.youtube-nocookie.com/embed/${id}?autoplay=1&rel=0`;youtubeLink.href=`https://www.youtube.com/watch?v=${id}`;videoModal.classList.add('open');videoModal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeVideo(){videoModal.classList.remove('open');videoModal.setAttribute('aria-hidden','true');youtubePlayer.src='about:blank';document.body.style.overflow=''}
document.querySelectorAll('.video-open').forEach(button=>button.addEventListener('click',()=>openVideo(button.dataset.videoId,button.dataset.title)));
document.querySelector('.featured-play').addEventListener('click',()=>openVideo('gcNh17Ckjgg','How to properly squat for growth'));
document.querySelectorAll('[data-video-close]').forEach(button=>button.addEventListener('click',closeVideo));
const filterButtons=[...document.querySelectorAll('[data-filter]')],videoCards=[...document.querySelectorAll('.video-card')],videoSearch=document.getElementById('videoSearch');let activeFilter='all';
function filterVideos(){const query=videoSearch.value.trim().toLowerCase();let count=0;videoCards.forEach(card=>{const matchesCategory=activeFilter==='all'||card.dataset.category.includes(activeFilter);const matchesSearch=!query||card.dataset.search.includes(query)||card.textContent.toLowerCase().includes(query);const visible=matchesCategory&&matchesSearch;card.hidden=!visible;if(visible)count++});document.getElementById('videoCount').textContent=`${count} video${count===1?'':'s'}`;document.getElementById('videoEmpty').classList.toggle('show',count===0)}
filterButtons.forEach(button=>button.addEventListener('click',()=>{filterButtons.forEach(x=>x.classList.remove('active'));button.classList.add('active');activeFilter=button.dataset.filter;filterVideos()}));videoSearch.addEventListener('input',filterVideos);
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&videoModal.classList.contains('open'))closeVideo()});

const rewardButtons=[...document.querySelectorAll('[data-claim]')];let earnedXp=0;
try{earnedXp=Number(localStorage.getItem('form-earned-xp')||0)}catch(e){}
function renderRewards(){const total=2460+earnedXp;document.getElementById('currentXp').textContent=total.toLocaleString();document.getElementById('pointsTotal').textContent=total.toLocaleString();document.getElementById('leaderXp').textContent=`${total.toLocaleString()} XP`;document.getElementById('xpRemaining').textContent=`${Math.max(0,3000-total).toLocaleString()} XP`;document.getElementById('xpFill').style.width=`${Math.min(100,total/3000*100)}%`;rewardButtons.forEach((button,index)=>{let claimed=false;try{claimed=localStorage.getItem(`form-reward-${index}`)==='1'}catch(e){}if(claimed){button.textContent='Completed';button.disabled=true;button.closest('.challenge-card').classList.add('claimed')}})}
rewardButtons.forEach((button,index)=>button.addEventListener('click',()=>{if(button.disabled)return;const points=Number(button.dataset.claim);earnedXp+=points;try{localStorage.setItem('form-earned-xp',earnedXp);localStorage.setItem(`form-reward-${index}`,'1')}catch(e){}renderRewards();notify(`${button.dataset.action} · +${points} XP`)}));renderRewards();

const workoutTemplate=[
 {name:'Back squat',target:'4 sets · 6 reps',sets:4,weight:100,reps:6,rest:'2 min'},
 {name:'Romanian deadlift',target:'4 sets · 8 reps',sets:4,weight:80,reps:8,rest:'90 sec'},
 {name:'Bulgarian split squat',target:'3 sets · 10 each side',sets:3,weight:24,reps:10,rest:'75 sec'},
 {name:'Leg press',target:'4 sets · 10 reps',sets:4,weight:140,reps:10,rest:'90 sec'},
 {name:'Hamstring curl',target:'3 sets · 12 reps',sets:3,weight:45,reps:12,rest:'60 sec'},
 {name:'Sled push',target:'4 rounds · 20 metres',sets:4,weight:70,reps:20,rest:'60 sec'},
 {name:'Standing calf raise',target:'3 sets · 15 reps',sets:3,weight:60,reps:15,rest:'45 sec'}
];
const workoutTracker=document.getElementById('workoutTracker'),trackerExercises=document.getElementById('trackerExercises');let workoutState={started:null,effort:7,notes:'',exercises:[]},clockTimer;
function freshWorkout(){return{started:Date.now(),effort:7,notes:'',exercises:workoutTemplate.map(ex=>({...ex,notes:'',setsData:Array.from({length:ex.sets},()=>({weight:ex.weight,reps:ex.reps,rpe:7,done:false}))}))}}
function loadWorkout(){try{const saved=JSON.parse(localStorage.getItem('form-active-workout'));if(saved?.exercises?.length)return saved}catch(e){}return freshWorkout()}
function saveWorkout(){try{localStorage.setItem('form-active-workout',JSON.stringify(workoutState))}catch(e){}}
function renderTracker(){trackerExercises.innerHTML=workoutState.exercises.map((ex,exerciseIndex)=>`<article class="track-exercise ${exerciseIndex===0?'open':''}" data-exercise="${exerciseIndex}"><button class="exercise-head" type="button"><span class="track-number">${String(exerciseIndex+1).padStart(2,'0')}</span><div><h4>${ex.name}</h4><p>${ex.target} · ${ex.rest} rest</p></div><strong><span class="exercise-complete-count">${ex.setsData.filter(s=>s.done).length}</span>/${ex.setsData.length}</strong><span class="exercise-chevron">⌄</span></button><div class="set-panel"><div class="set-labels"><span>SET</span><span>KG</span><span>REPS</span><span>RPE</span><span>DONE</span></div>${ex.setsData.map((set,setIndex)=>`<div class="set-row ${set.done?'done':''}" data-set="${setIndex}"><b>${setIndex+1}</b><input type="number" inputmode="decimal" min="0" step="2.5" value="${set.weight}" aria-label="${ex.name} set ${setIndex+1} weight"><input type="number" inputmode="numeric" min="0" value="${set.reps}" aria-label="${ex.name} set ${setIndex+1} reps"><input type="number" inputmode="decimal" min="1" max="10" step=".5" value="${set.rpe}" aria-label="${ex.name} set ${setIndex+1} RPE"><button class="set-check" type="button" aria-label="Mark set ${setIndex+1} complete"><span data-icon="check"></span></button></div>`).join('')}<label class="exercise-notes">Comment for your coach<input value="${ex.notes||''}" placeholder="Technique, pain, difficulty or a personal best…"></label><button class="add-set" type="button">+ Add another set</button></div></article>`).join('');trackerExercises.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[el.dataset.icon]||''}</svg>`});updateTrackerSummary()}
function elapsedSeconds(){return workoutState.started?Math.max(0,Math.floor((Date.now()-workoutState.started)/1000)):0}function formatClock(seconds){return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
function updateClock(){const seconds=elapsedSeconds();document.getElementById('workoutClock').textContent=formatClock(seconds);document.getElementById('summaryDuration').textContent=`${Math.floor(seconds/60)} min`}
function updateTrackerSummary(){const sets=workoutState.exercises.flatMap(ex=>ex.setsData),done=sets.filter(s=>s.done),volume=done.reduce((sum,s)=>sum+(Number(s.weight)||0)*(Number(s.reps)||0),0);document.getElementById('summaryVolume').textContent=`${volume.toLocaleString()} kg`;document.getElementById('summarySets').textContent=`${done.length} sets`;document.getElementById('trackerProgressText').textContent=`${done.length} of ${sets.length} sets`;document.getElementById('trackerProgressFill').style.width=`${sets.length?done.length/sets.length*100:0}%`;document.getElementById('effortValue').textContent=workoutState.effort;saveWorkout()}
function openWorkout(){workoutState=loadWorkout();workoutState.exercises.forEach(ex=>{ex.rest='20 sec'});renderTracker();document.querySelector('.tracker-header h2').textContent=workoutState.name||'Lower body power';document.getElementById('sessionEffort').value=workoutState.effort;document.getElementById('effortValue').textContent=workoutState.effort;document.getElementById('sessionNotes').value=workoutState.notes;workoutTracker.classList.add('open');workoutTracker.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';clearInterval(clockTimer);updateClock();clockTimer=setInterval(updateClock,1000)}
function closeWorkout(){workoutTracker.classList.remove('open');workoutTracker.setAttribute('aria-hidden','true');document.body.style.overflow='';clearInterval(clockTimer);saveWorkout()}
document.getElementById('trackerClose').addEventListener('click',closeWorkout);trackerExercises.addEventListener('click',event=>{const article=event.target.closest('.track-exercise');if(!article)return;const exerciseIndex=Number(article.dataset.exercise);if(event.target.closest('.exercise-head')){article.classList.toggle('open');return}const row=event.target.closest('.set-row');if(event.target.closest('.set-check')&&row){const set=workoutState.exercises[exerciseIndex].setsData[Number(row.dataset.set)];set.done=!set.done;row.classList.toggle('done',set.done);article.querySelector('.exercise-complete-count').textContent=workoutState.exercises[exerciseIndex].setsData.filter(s=>s.done).length;updateTrackerSummary();return}if(event.target.closest('.add-set')){workoutState.exercises[exerciseIndex].setsData.push({weight:0,reps:0,rpe:7,done:false});renderTracker();trackerExercises.querySelector(`[data-exercise="${exerciseIndex}"]`).classList.add('open')}});
trackerExercises.addEventListener('input',event=>{const article=event.target.closest('.track-exercise');if(!article)return;const ex=workoutState.exercises[Number(article.dataset.exercise)];if(event.target.closest('.exercise-notes'))ex.notes=event.target.value;const row=event.target.closest('.set-row');if(row){const inputs=[...row.querySelectorAll('input')],set=ex.setsData[Number(row.dataset.set)];set.weight=Number(inputs[0].value);set.reps=Number(inputs[1].value);set.rpe=Number(inputs[2].value)}updateTrackerSummary()});
document.getElementById('sessionEffort').addEventListener('input',event=>{workoutState.effort=Number(event.target.value);document.getElementById('effortValue').textContent=workoutState.effort;saveWorkout()});document.getElementById('sessionNotes').addEventListener('input',event=>{workoutState.notes=event.target.value;saveWorkout()});
document.getElementById('finishWorkout').addEventListener('click',()=>{const completed=workoutState.exercises.flatMap(ex=>ex.setsData).filter(set=>set.done).length;if(!completed){notify('Complete at least one set before finishing.');return}try{const history=JSON.parse(localStorage.getItem('form-workout-history')||'[]');history.unshift({...workoutState,finished:Date.now()});localStorage.setItem('form-workout-history',JSON.stringify(history.slice(0,12)))}catch(e){}closeWorkout();try{localStorage.removeItem('form-active-workout')}catch(e){}notify(`Workout saved · ${completed} sets completed`);workoutState=freshWorkout()});

// Expanded app navigation and purchase / booking journeys
Object.assign(titles,{onDemand:'Train on your time.',membershipShop:'Choose your membership.',voucherShop:'Give the gift of movement.',productGroups:'Find your next session.',about:'Meet Holly Margot.',news:'The latest from Holly Margot.',contacts:'Your people.',profileHub:'Your profile.',watchlist:'Saved for later.',qrCode:'Your member pass.',passwordPage:'Protect your account.',cardsPage:'Your payment cards.',familyPage:'Linked family members.',journey:'Complete your selection.'});
document.querySelectorAll('[data-action-toast]').forEach(button=>button.addEventListener('click',()=>notify(button.dataset.actionToast)));
document.querySelectorAll('.subnav button').forEach(button=>button.addEventListener('click',()=>{button.parentElement.querySelectorAll('button').forEach(item=>item.classList.remove('active'));button.classList.add('active');notify(`${button.textContent} selected`)}));

const journeyState={kind:'booking',product:'',price:'',step:1,returnView:'productGroups',selection:''};
const journeyContent=document.getElementById('journeyContent'),journeyNext=document.getElementById('journeyNext');
function journeyOptions(items){return `<div class="journey-options">${items.map((item,index)=>`<button class="journey-option ${index===0?'selected':''}" type="button" data-choice="${item[0]}"><span><strong>${item[0]}</strong><small>${item[1]}</small></span><b>${index===0?'✓':'›'}</b></button>`).join('')}</div>`}
function renderJourney(){const kind=journeyState.kind,step=journeyState.step;document.querySelectorAll('.journey-steps span').forEach((node,index)=>{node.classList.toggle('active',index===step-1);node.classList.toggle('done',index<step-1)});document.getElementById('stepTwoLabel').textContent=kind==='booking'?'Date / time':kind==='voucher'?'Voucher type':'Membership';document.getElementById('orderProduct').textContent=journeyState.product;document.getElementById('orderPrice').textContent=journeyState.price;const titlesByStep=['Confirm your choice.','Make it yours.','Who is this for?','Review and pay.'];document.getElementById('journeyTitle').textContent=titlesByStep[step-1];journeyNext.innerHTML=step===4?'Pay securely <span data-icon="lock"></span>':'Continue <span data-icon="arrow"></span>';if(step===1){journeyContent.innerHTML=`<div class="selection-hero"><p>You selected</p><h3>${journeyState.product}</h3><span>${journeyState.price}</span><p>You can review the details before continuing.</p></div>`}else if(step===2&&kind==='booking'){journeyContent.innerHTML=journeyOptions([['Thursday 10 September · 10:30','Jordan Taylor · Studio 2'],['Saturday 12 September · 09:00','Maya Chen · Main floor'],['Tuesday 15 September · 17:30','Jordan Taylor · Studio 1']])}else if(step===2&&kind==='voucher'){journeyContent.innerHTML=journeyOptions([['Digital voucher','Delivered instantly by email'],['Premium printed card','Posted within two working days'],['Send on a chosen date','Schedule email delivery']])}else if(step===2){journeyContent.innerHTML=journeyOptions([['Monthly membership','Flexible monthly billing'],['Annual membership','Save two months'],['Start next month','Schedule your start date']])}else if(step===3){journeyContent.innerHTML=`<div class="participant-form"><label>First name<input value="Alex"></label><label>Last name<input value="Morgan"></label><label class="wide">Email address<input type="email" value="alex.morgan@example.com"></label><label class="wide">Participant<select><option>Myself</option><option>Family member</option><option>Someone else</option></select></label></div>`}else{journeyContent.innerHTML=`<div class="checkout-card"><span class="tile-icon"><span data-icon="card"></span></span><div><strong>Visa ending 4242</strong><p>Expires 08/29 · Default card</p></div><b>✓</b></div><label class="setting-row"><span><strong>Accept terms and cancellation policy</strong><small>Your payment is processed securely</small></span><input type="checkbox" checked><i></i></label>`}journeyContent.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${icons[el.dataset.icon]||''}</svg>`});journeyNext.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${icons[el.dataset.icon]||''}</svg>`})}
document.querySelectorAll('.journey-start').forEach(button=>button.addEventListener('click',()=>{journeyState.kind=button.dataset.kind;journeyState.product=button.dataset.product;journeyState.price=button.dataset.price;journeyState.step=1;journeyState.returnView=journeyState.kind==='membership'?'membershipShop':journeyState.kind==='voucher'?'voucherShop':'productGroups';renderJourney();showView('journey')}));
journeyContent.addEventListener('click',event=>{const option=event.target.closest('.journey-option');if(!option)return;journeyContent.querySelectorAll('.journey-option').forEach(item=>{item.classList.remove('selected');item.querySelector('b').textContent='›'});option.classList.add('selected');option.querySelector('b').textContent='✓';journeyState.selection=option.dataset.choice;document.getElementById('orderDetail').textContent=option.dataset.choice});
journeyNext.addEventListener('click',()=>{if(journeyState.step<4){journeyState.step++;renderJourney();window.scrollTo({top:0,behavior:'smooth'})}else{notify(`${journeyState.kind==='booking'?'Booking confirmed':'Purchase complete'} · Confirmation sent`);showView(journeyState.returnView)}});
document.getElementById('journeyBack').addEventListener('click',()=>{if(journeyState.step>1){journeyState.step--;renderJourney()}else showView(journeyState.returnView)});

const profileForm=document.getElementById('profileForm');try{const profileData=JSON.parse(localStorage.getItem('form-profile')||'null');if(profileData)Object.entries(profileData).forEach(([key,value])=>{if(profileForm.elements[key])profileForm.elements[key].value=value})}catch(e){}
profileForm.addEventListener('submit',event=>{event.preventDefault();const data=Object.fromEntries(new FormData(profileForm));try{localStorage.setItem('form-profile',JSON.stringify(data))}catch(e){}notify('Profile changes saved')});
document.querySelectorAll('[data-account-action]').forEach(button=>button.addEventListener('click',()=>notify(`${button.dataset.accountAction} opened`)));document.getElementById('addPayment').addEventListener('click',()=>notify('Secure card setup opened'));document.getElementById('addCredit').addEventListener('click',()=>notify('Choose an amount to add to your wallet'));document.getElementById('exportActivity').addEventListener('click',()=>notify('Your activity export is being prepared'));
document.querySelectorAll('.setting-row input').forEach((input,index)=>{try{const value=localStorage.getItem(`form-setting-${index}`);if(value!==null)input.checked=value==='true'}catch(e){}input.addEventListener('change',()=>{try{localStorage.setItem(`form-setting-${index}`,input.checked)}catch(e){}notify('Preference updated')})});
function renderAccountActivity(){const feed=document.getElementById('activityFeed');if(feed.dataset.hydrated)return;let history=[];try{history=JSON.parse(localStorage.getItem('form-workout-history')||'[]')}catch(e){}if(!history.length)return;feed.dataset.hydrated='true';const workoutRows=history.slice(0,3).map(workout=>{const sets=workout.exercises.flatMap(ex=>ex.setsData),completed=sets.filter(set=>set.done),volume=completed.reduce((sum,set)=>sum+(Number(set.weight)||0)*(Number(set.reps)||0),0),date=new Date(workout.finished||workout.started).toLocaleDateString('en-GB',{day:'numeric',month:'short'});return `<article><span class="activity-icon"><span data-icon="bolt"></span></span><div><strong>Lower body power</strong><p>${date} · ${completed.length} sets · ${volume.toLocaleString()} kg</p></div><em>RPE ${workout.effort}</em></article>`}).join('');feed.innerHTML=workoutRows+feed.innerHTML;feed.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[el.dataset.icon]||''}</svg>`})}

// Performance Center
titles.activity='Your Performance Center.';
const performanceTabs=[...document.querySelectorAll('[data-performance-tab]')];
performanceTabs.forEach(button=>button.addEventListener('click',()=>{performanceTabs.forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('[data-performance-panel]').forEach(panel=>panel.classList.toggle('active',panel.dataset.performancePanel===button.dataset.performanceTab))}));

const builderLibrary=document.getElementById('exerciseBuilderLibrary'),workoutDropZone=document.getElementById('workoutDropZone'),builderCount=document.getElementById('builderExerciseCount');
let builderExercises=[
 {name:'Back squat',category:'lower',rest:120,sets:4,reps:6,thumb:'squat-thumb'},
 {name:'Romanian deadlift',category:'lower',rest:90,sets:4,reps:8,thumb:'hinge-thumb'},
 {name:'Bulgarian split squat',category:'lower',rest:75,sets:3,reps:10,thumb:'split-thumb'}
];
try{const saved=JSON.parse(localStorage.getItem('form-workout-builder')||'null');if(Array.isArray(saved)&&saved.length)builderExercises=saved}catch(e){}
function performanceIcon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||''}</svg>`}
function renderWorkoutBuilder(){workoutDropZone.innerHTML=builderExercises.map((exercise,index)=>`<article class="build-exercise" draggable="true" data-build-index="${index}"><span class="drag-handle" aria-hidden="true">⋮⋮</span><div class="exercise-video-thumb ${exercise.thumb||'squat-thumb'}">${performanceIcon('play')}</div><div><strong>${exercise.name}</strong><small>Indicative video · ${exercise.category}</small></div><div class="build-controls"><label>SETS<input type="number" min="1" max="12" value="${exercise.sets}" data-build-field="sets"></label><label>REPS<input type="number" min="1" max="100" value="${exercise.reps}" data-build-field="reps"></label><label>REST<input type="number" min="0" max="600" step="15" value="${exercise.rest}" data-build-field="rest"></label></div><button class="remove-build-exercise" type="button" aria-label="Remove ${exercise.name}">×</button></article>`).join('');const totalSets=builderExercises.reduce((sum,item)=>sum+Number(item.sets),0);builderCount.textContent=`${builderExercises.length} exercise${builderExercises.length===1?'':'s'} · ${totalSets} sets`;try{localStorage.setItem('form-workout-builder',JSON.stringify(builderExercises))}catch(e){}}
function addBuilderExercise(source){const item={name:source.dataset.builderName,category:source.dataset.builderCategory,rest:Number(source.dataset.builderRest),sets:Number(source.dataset.builderSets),reps:Number(source.dataset.builderReps),thumb:source.querySelector('.exercise-video-thumb')?.classList[1]||'squat-thumb'};builderExercises.push(item);renderWorkoutBuilder();notify(`${item.name} added to workout`)}
builderLibrary.addEventListener('click',event=>{const button=event.target.closest('button'),source=event.target.closest('[data-builder-name]');if(button&&source)addBuilderExercise(source)});
builderLibrary.addEventListener('dragstart',event=>{const source=event.target.closest('[data-builder-name]');if(!source)return;source.classList.add('dragging');event.dataTransfer.setData('text/plain',source.dataset.builderName);event.dataTransfer.effectAllowed='copy'});
builderLibrary.addEventListener('dragend',event=>event.target.closest('[data-builder-name]')?.classList.remove('dragging'));
workoutDropZone.addEventListener('dragover',event=>{event.preventDefault();event.dataTransfer.dropEffect='copy'});
workoutDropZone.addEventListener('drop',event=>{event.preventDefault();const source=[...builderLibrary.querySelectorAll('[data-builder-name]')].find(item=>item.dataset.builderName===event.dataTransfer.getData('text/plain'));if(source)addBuilderExercise(source)});
workoutDropZone.addEventListener('click',event=>{const remove=event.target.closest('.remove-build-exercise');if(!remove)return;const index=Number(remove.closest('[data-build-index]').dataset.buildIndex);builderExercises.splice(index,1);renderWorkoutBuilder()});
workoutDropZone.addEventListener('input',event=>{const field=event.target.dataset.buildField;if(!field)return;const index=Number(event.target.closest('[data-build-index]').dataset.buildIndex);builderExercises[index][field]=Math.max(0,Number(event.target.value));renderWorkoutBuilder()});
let movingBuilderIndex=null;workoutDropZone.addEventListener('dragstart',event=>{const item=event.target.closest('[data-build-index]');if(!item)return;movingBuilderIndex=Number(item.dataset.buildIndex);event.dataTransfer.effectAllowed='move'});workoutDropZone.addEventListener('dragover',event=>{event.preventDefault();event.target.closest('[data-build-index]')?.classList.add('drag-over')});workoutDropZone.addEventListener('dragleave',event=>event.target.closest('[data-build-index]')?.classList.remove('drag-over'));workoutDropZone.addEventListener('drop',event=>{const target=event.target.closest('[data-build-index]');if(!target||movingBuilderIndex===null)return;event.preventDefault();const targetIndex=Number(target.dataset.buildIndex),[moved]=builderExercises.splice(movingBuilderIndex,1);builderExercises.splice(targetIndex,0,moved);movingBuilderIndex=null;renderWorkoutBuilder()});
const exerciseSearch=document.getElementById('exerciseSearch');let exerciseFilter='all';function filterExerciseLibrary(){const query=exerciseSearch.value.trim().toLowerCase();builderLibrary.querySelectorAll('[data-builder-name]').forEach(item=>item.hidden=!((exerciseFilter==='all'||item.dataset.builderCategory===exerciseFilter)&&item.dataset.builderName.toLowerCase().includes(query)))}exerciseSearch.addEventListener('input',filterExerciseLibrary);document.querySelectorAll('[data-exercise-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-exercise-filter]').forEach(item=>item.classList.remove('active'));button.classList.add('active');exerciseFilter=button.dataset.exerciseFilter;filterExerciseLibrary()}));
document.getElementById('clearWorkoutBuild').addEventListener('click',()=>{builderExercises=[];renderWorkoutBuilder();notify('Workout canvas cleared')});
function assignBuiltWorkout(){if(!builderExercises.length){notify('Add at least one exercise first.');return false}const name=document.getElementById('builderWorkoutName').value.trim()||'Custom workout';const active={started:Date.now(),effort:7,feeling:'Good',notes:'',name,exercises:builderExercises.map(ex=>({name:ex.name,target:`${ex.sets} sets · ${ex.reps} reps`,sets:ex.sets,weight:0,reps:ex.reps,rest:`${ex.rest} sec`,notes:'',setsData:Array.from({length:ex.sets},()=>({weight:0,reps:ex.reps,rpe:7,done:false}))}))};try{localStorage.setItem('form-active-workout',JSON.stringify(active));localStorage.setItem('form-workout-builder',JSON.stringify(builderExercises))}catch(e){}notify(`${name} saved and assigned`);return true}
document.getElementById('saveWorkoutBuild').addEventListener('click',assignBuiltWorkout);document.getElementById('quickStartWorkout').addEventListener('click',()=>{if(assignBuiltWorkout())setTimeout(openWorkout,180)});renderWorkoutBuilder();

let restTimerInterval=null,restSeconds=0;const restPanel=document.getElementById('restTimerPanel'),restValue=document.getElementById('restTimerValue'),restExercise=document.getElementById('restTimerExercise');function formatRest(value){return `${String(Math.floor(value/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`}function stopRestTimer(){clearInterval(restTimerInterval);restTimerInterval=null;restPanel.classList.remove('show');restPanel.style.setProperty('--rest-progress','0deg')}function startRestTimer(seconds,exercise){stopRestTimer();restSeconds=20;restValue.textContent=formatRest(restSeconds);restExercise.textContent=exercise;restPanel.style.setProperty('--rest-progress','360deg');restPanel.classList.add('show');restTimerInterval=setInterval(()=>{restSeconds--;restValue.textContent=formatRest(Math.max(0,restSeconds));restPanel.style.setProperty('--rest-progress',`${Math.max(0,restSeconds)/20*360}deg`);if(restSeconds<=0){stopRestTimer();notify('Rest complete · ready for your next set')}},1000)}
trackerExercises.addEventListener('click',event=>{const check=event.target.closest('.set-check'),article=event.target.closest('.track-exercise'),row=event.target.closest('.set-row');if(!check||!article||!row)return;setTimeout(()=>{const ex=workoutState.exercises[Number(article.dataset.exercise)],set=ex.setsData[Number(row.dataset.set)];if(set.done){const raw=String(ex.rest||'60 sec');const seconds=raw.includes('min')?Math.round(parseFloat(raw)*60):parseInt(raw,10)||60;startRestTimer(seconds,ex.name)}})});document.getElementById('restTimerSkip').addEventListener('click',()=>{stopRestTimer();notify('Rest skipped')});document.getElementById('trackerClose').addEventListener('click',stopRestTimer);document.getElementById('finishWorkout').addEventListener('click',stopRestTimer);
document.querySelectorAll('[data-feeling]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-feeling]').forEach(item=>item.classList.remove('active'));button.classList.add('active');workoutState.feeling=button.dataset.feeling;saveWorkout()}));document.querySelectorAll('[data-start],#quickStartWorkout').forEach(button=>button.addEventListener('click',()=>setTimeout(()=>{const feeling=workoutState.feeling||'Good';document.querySelectorAll('[data-feeling]').forEach(item=>item.classList.toggle('active',item.dataset.feeling===feeling))},0)));

let calories=1860;document.getElementById('addMealButton').addEventListener('click',()=>{const log=document.getElementById('dailyMealLog'),row=document.createElement('div');row.innerHTML='<span>19:30</span><strong>Chicken, rice & seasonal greens</strong><em>480 kcal</em>';log.appendChild(row);calories+=480;document.getElementById('caloriesConsumed').textContent=calories.toLocaleString();document.querySelector('.calorie-card h3').textContent=`${Math.max(0,2450-calories).toLocaleString()} kcal remaining.`;document.getElementById('calorieRing').style.background=`conic-gradient(var(--lime) 0 ${Math.min(100,calories/2450*100)}%,#292f2c ${Math.min(100,calories/2450*100)}% 100%)`;notify('Meal added to today’s tracker')},{once:true});document.querySelectorAll('[data-add-recipe]').forEach(button=>button.addEventListener('click',()=>notify(`${button.dataset.addRecipe} added to the meal plan`)));
document.getElementById('recipeUpload').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;const name=file.name.replace(/\.[^.]+$/,'').replace(/[-_]/g,' '),card=document.createElement('article');card.innerHTML=`<div class="recipe-art recipe-green">${performanceIcon('document')}<b>YOUR RECIPE</b></div><div><small>COACH UPLOAD</small><h3>${name}</h3><p>Custom recipe ready to personalise and assign.</p><footer><strong>Custom</strong><span>Nutrition details</span><button type="button">Edit recipe</button></footer></div>`;document.getElementById('recipeGrid').prepend(card);notify(`${file.name} uploaded to your recipe library`);event.target.value=''});

document.querySelectorAll('.reaction-button').forEach((button,index)=>{try{if(localStorage.getItem(`form-reaction-${index}`)==='1')button.classList.add('active')}catch(e){}button.addEventListener('click',()=>{const active=button.classList.toggle('active'),count=button.querySelector('span');count.textContent=Number(count.textContent)+(active?1:-1);try{localStorage.setItem(`form-reaction-${index}`,active?'1':'0')}catch(e){}if(active)notify(button.dataset.reaction==='highfive'?'High-five sent!':'Reaction added')})});
const habits=[...document.querySelectorAll('.habit-list input')];function updateHabits(){const total=habits.filter(input=>input.checked).length;document.getElementById('habitScore').textContent=`${total} / ${habits.length}`;habits.forEach((input,index)=>{try{localStorage.setItem(`form-habit-${index}`,String(input.checked))}catch(e){}})}habits.forEach((input,index)=>{try{const saved=localStorage.getItem(`form-habit-${index}`);if(saved!==null)input.checked=saved==='true'}catch(e){}input.addEventListener('change',()=>{updateHabits();notify(input.checked?'Habit completed · keep going!':'Habit marked incomplete')})});updateHabits();

let powerliftingReturnView='activity';function openPowerliftingSummary(fromView){powerliftingReturnView=fromView;showView('workoutSummary')}document.getElementById('viewPowerliftingSession').addEventListener('click',()=>openPowerliftingSummary('activity'));document.getElementById('closePowerliftingPreview').addEventListener('click',()=>showView(powerliftingReturnView));document.querySelectorAll('[data-session-toast]').forEach(button=>button.addEventListener('click',()=>notify(`${button.dataset.sessionToast} preview opened`)));document.querySelectorAll('.powerlifting-video').forEach(button=>button.addEventListener('click',()=>openVideo(button.dataset.videoId,button.dataset.title)));
const powerliftingSession=[
 {name:'Competition back squat',target:'4 sets · 5 reps',sets:4,weight:100,reps:5,rest:'20 sec'},
 {name:'Paused bench press',target:'4 sets · 5 reps',sets:4,weight:70,reps:5,rest:'20 sec'},
 {name:'Competition deadlift',target:'4 sets · 3 reps',sets:4,weight:120,reps:3,rest:'20 sec'},
 {name:'Chest-supported row',target:'3 sets · 10 reps',sets:3,weight:40,reps:10,rest:'20 sec'},
 {name:'Weighted plank',target:'3 sets · 30 sec',sets:3,weight:10,reps:30,rest:'20 sec'}
];
document.getElementById('startPowerliftingWorkout').addEventListener('click',()=>{const active={started:Date.now(),effort:7,feeling:'Good',notes:'',name:'Powerlifting foundations',source:'self-guided',exercises:powerliftingSession.map(ex=>({...ex,notes:'',setsData:Array.from({length:ex.sets},()=>({weight:ex.weight,reps:ex.reps,rpe:7,done:false}))}))};try{localStorage.setItem('form-active-workout',JSON.stringify(active))}catch(e){}openWorkout();notify('Self-guided powerlifting session started')});
document.getElementById('homeStartNextWorkout').addEventListener('click',()=>document.getElementById('startPowerliftingWorkout').click());
document.getElementById('startPowerliftingFromCard').addEventListener('click',()=>document.getElementById('startPowerliftingWorkout').click());
document.getElementById('homeViewNextWorkout').addEventListener('click',()=>openPowerliftingSummary('home'));
